name: First Github Actions Workflow
on:
  push:
    branches:
      - main
    # paths-ignore:
    #   - ".github/workflows/*"
#   pull_request:
#     types:

#       - opened
#       - edited
#   workflow_dispatch:
jobs:
  NodeJs_Github_Actions:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from repository
        uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Cache the dependency
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dependency-module-${{ hashFiles('**/package-lock.json')}}
      - name: Run the node command
        run: npm ci
      - name: Docker Build
        run: docker build -t node:latest .

      - name: login to dockerhub repository
        uses: docker/login-action@v2.2.0
        with:
          username: santoshpusparajs
          #   ${{secrets.DOCKER_USERNAME}}
          password: San@9486849031
          #   ${{secrets.DOCKER_PASSWORD}}
      - name: Pushing the docker image to repository
        run: |
          docker tag node:latest santoshpusparajs/express-js-application:myfirstimagepush
          docker push santoshpusparajs/express-js-application:myfirstimagepush
